### PR TITLE
New API: Metadata::new_from_app1_segment

### PR DESCRIPTION
**Pull request by hfiguiere**
Draft as it requires https://github.com/felixc/gexiv2-sys/pull/21 

Tested it locally.

Use case with https://github.com/maxicarlos08/gphoto2-rs/pull/53

### CODE REVIEW

**Comment by hfiguiere** [comment]
Requirements have been released.

**Review by felixc — APPROVED** [review]
Thank you for adding this!

Do you happen to have the contents of an app1 segment handy, so we could add a test [like this one](https://github.com/felixc/rexiv2/blob/24e9cdd142ceef61a601341fc01783a673d3b4e1/tst/main.rs#L49-L54) or [like this](https://github.com/felixc/gexiv2-sys/blob/1581c5d6f66552145afee979012a6a1a00d68b73/examples/open_buf.rs#L12-L27)?

It's OK if not; I'm happy to merge either way.

**Comment by felixc** [comment]
I updated `Cargo.toml` to use the latest version of `glib-sys` to match `gexiv2-sys`, which fixed a build failure that only appeared if you build with the `raw-tag-access` feature.

I've also reconfigured CircleCI to run builds for pull requests and not just the `main` branch.

**Comment by felixc** [comment]
Right; will need to bump MSRV here too.

**Comment by hfiguiere** [comment]
Here is a sample:

[exif_IMG_6036.JPG.bin.gz](https://github.com/felixc/rexiv2/files/10420719/exif_IMG_6036.JPG.bin.gz)

**Comment by hfiguiere** [comment]
I added a test for it now.

**Comment by felixc** [comment]
Thank you very much!

I hope it's OK with you that I added you to the contributors list in `CONTRIBUTORS.md`

I appreciate the test, too. It's something I didn't add enough to the codebase early on, so now I'm trying to bring up the coverage on new code at least to make it safer to make changes in the future. I did end up changing it to use a smaller buffer to minimize the size of the repo diffs/downloads, though.

Thanks again for the contribution -- I'll push out a new version including this soon!

**Review by felixc — APPROVED** [review]

**Pull request merged**
